### ISSUE TITLE
Unit tests for data compatibility with the chain

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/substrate-client#35]
To avoid type changes on the chain that breaks the client. we need to add unit tests to make sure the "Getters" of the objects always work and return the expected data.

- The test should cover all Get methods
- Test against actual devnet
- Create constant of object ids that are used in the tests 

> There is a problem that since we don't own the objects that we test against the object might get deleted and the tests would fail. One solution is that the tests can create all (or some of) the objects that we check this way we can also validate the create/update method. but this will pollute the chain with many unwanted objects.

A proper solution for this is that the test can spawn an instance of the chain (in a container) and then the tests can then create the objects (farms, nodes, contracts, twins, etc...) the test that types compatibility is still valid. This would mean this docker image need to update with latest devnet before the test is executed

@DylanVerstraete what do you think?

**Comment by Eslam-Nawara** [comment]
I've covered all the getters against the devnet and created the extrinsic tests on a local node too
