### ISSUE TITLE
Implement third party billing services events / types and calls

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/substrate-client#46]
### Related to TFChain

- https://github.com/threefoldtech/tfchain/issues/445
- https://github.com/threefoldtech/tfchain/issues/562

### TODO

- [x] Struct
  - ServiceContract
  - ServiceContractBill
  - ServiceContractState
- [x] Events
  - ServiceContractCreated
  - ServiceContractMetadataSet
  - ServiceContractFeesSet
  - ServiceContractApproved
  - ServiceContractCanceled
  - ServiceContractBilled
- [x] Extrinsics
  - service_contract_create()
  - service_contract_set_metadata()
  - service_contract_set_fees()
  - service_contract_approve()
  - service_contract_reject()
  - service_contract_cancel()
  - service_contract_bill()

**Comment by DylanVerstraete** [comment]
Time to complete: 4 hours

**Comment by A-Harby** [comment]
servicecontractCreate
![image](https://user-images.githubusercontent.com/109473873/214642647-68d922b5-404f-4953-9344-3a55bc5cfa98.png)
![image](https://user-images.githubusercontent.com/109473873/214646367-0ff70c7c-0485-4be2-9b35-7dc50af0a039.png)
https://github.com/threefoldtech/tfchain/issues/562#issuecomment-1403925274
https://github.com/threefoldtech/tfchain/issues/445#issuecomment-1403963829
