### ISSUE TITLE
repo documentation

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/substrate-client#48]
home page doesn't tell much

## checklist 
- have an introduction to the project
- show status of the tests and code coverage
- how to run in production e.g if it was a binary or something the enduser needs to download 
- how to run in development as a developer (it's fine to link to another page)
- should have a link to internal docs for development
  - how to get the code  
  - how to configure the editor/IDE
  - how to run the tests
  - how to write new tests
  - have the workflows documented
  - have the releasing process documented

**Comment by A-Harby** [comment]
Verified.
[Readme](https://github.com/threefoldtech/substrate-client/blob/master/readme.md)
