### ISSUE TITLE
GetZosVersion returns *string

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/substrate-client#54]
It's not good to return *string, string is already a sort of a smart pointer hence returning a *string is not good (although a *string has it's uses). This function should never return a *string. if an error occur an empty string "" is returned with the error.

**Comment by mohamedamer453** [comment]
Verified from https://github.com/threefoldtech/substrate-client/pull/55/files. [`GetZosVersion`](https://github.com/threefoldtech/substrate-client/blob/master/zos_version.go#L9) now returns a `string` not a `*string` and in case of errors, it now returns an empty string with the error message.
