### ISSUE TITLE
Balance issue

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/substrate-client#79]
I tried to compare the balance from GetBalance and GetAccount but they are different
- the first one GetBalance is correct
- network: qa

![Screenshot from 2023-01-31 12-00-53](https://user-images.githubusercontent.com/47260239/215729558-c19d32cb-5cd8-474c-b4ea-ad7c01744411.png)

**Comment by renauter** [comment]
Indeed, I checked and `GetAccount()` does not return correct balance values
For some reason values are `4294967296` times what int should be...
Let me check

**Comment by renauter** [comment]
I still don't get why but using a local `AccountInfo` struct (instead of the remote one) fixed it
